# =========================
# DATABASE CONFIGURATION
# =========================

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/library_management}
spring.datasource.username=${DB_USERNAME:library_user}
spring.datasource.password=${DB_PASSWORD:library_password}
spring.datasource.driver-class-name=org.postgresql.Driver

# =========================
# JPA / HIBERNATE
# =========================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# =========================
# HIBERNATE BATCH (for saveAll performance)
# =========================

spring.jpa.properties.hibernate.jdbc.batch_size=50
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true

# =========================
# SERVER
# =========================

server.port=9090

# =========================
# FILE UPLOADS (CSV IMPORT)
# =========================

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Root logging level
logging.level.root=INFO

# Your application logs
logging.level.com.library.library_management=DEBUG

# Save logs to file
logging.file.name=logs/library-management.log